document.write("<p><select>
<option>ファイル</option>
<option>----------------</option>
<option>新規作成</option>
<option>開く...</option>
<option>保存</option>
<option>名前を付けて保存</option>
<option>終了</option>
</select><select>
<option>編集</option>
<option>----------------</option>
<option>切取り</option>
<option>コピー</option>
<option>貼付け</option>
<option>すべて選択</option>
</select><select>
<option>ヘルプ</option>
<option>----------------</option>
<option>ヘルプ</option>
<option>バージョン</option>
</select></p>");
